const SCREENS = {
    INTRO: 'INTRO',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    WELCOME: 'WELCOME',
    
    ADDSCREEN: 'ADDSCREEN',
    HOMESCREEN: 'HOMESCREEN',
    HISTORYSCREEN: 'HISTORYSCREEN',
    ACCOUNTSCREEN: 'ACCOUNTSCREEN',
    CUSTOMERLISTSCREEN: 'CUSTOMERLISTSCREEN',
}

export default SCREENS;