const SCREENS = {
  INTRO: 'INTRO',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  WELCOME: 'WELCOME',

  // ADMIN SCREENS
  USERLISTSCREEN: 'USERLISTSCREEN',
  DASHBOARDSCREEN: 'DASHBOARDSCREEN',

  // USER SCREENS
  TEMPADD: 'TEMPADD',
  ADDSCREEN: 'ADD',
  HOMESCREEN: 'HOMESCREEN',
  HISTORYSCREEN: 'HISTORYSCREEN',
  PRODUCTSCREEN: 'PRODUCTSCREEN',
  ACCOUNTSCREEN: 'ACCOUNTSCREEN',
  CUSTOMERLISTSCREEN: 'CUSTOMERLISTSCREEN',

  VIEWCUSTOMERPROFILESCREEN: 'VIEWCUSTOMERPROFILESCREEN',
  EDITCUSTOMERPROFILESCREEN: 'EDITCUSTOMERPROFILESCREEN',

  ADDSALESCREEN: 'ADDSALE',
  ADDUTANGSCREEN: 'ADDUTANG',
  ADDPAYMENTSCREEN: 'ADDPAYMENT',
  ADDCUSTOMERSCREEN: 'ADDCUSTOMER',

  // GENERAL
  NOTIFICATIONSCREEN: 'NOTIFICATIONSCREEN',
};

export default SCREENS;
